"""add_listening_sessions_table

Revision ID: 0887be634b09
Revises: 2a12566ae957
Create Date: 2025-06-28 17:45:57.783260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0887be634b09'
down_revision = '2a12566ae957'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###